# [connections.postgres]
# dialect = "postgresql"
# username = "postgres"
# password = "postgres"
# host = "localhost"
# database = "postgres"


[connections]
    [connections.postgresql]
    dialect = "postgresql"
    username = "postgres"
    password = "postgres"
    host = "localhost"
    port = 5432
    database = "postgres"
